apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: bank-catalog-entity-upsert
  title: Bank Catalog - Entity Upsert (Create/Update)
  description: bank-catalog repo içinde Domain/System/Component/API/Resource/Group entity oluşturur veya günceller (PR açar).
spec:
  owner: group:platform-engineering
  type: catalog

  parameters:
    - title: Hedef repo ve temel bilgiler
      required: [catalogRepoUrl, kind, entityName, owner]
      properties:
        catalogRepoUrl:
          title: bank-catalog repo
          type: string
          description: bank-catalog repository URL (RepoUrlPicker)
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: ['github.com']
        kind:
          title: Entity Kind
          type: string
          enum: [Domain, System, Component, API, Resource, Group]
        entityName:
          title: metadata.name (kebab-case)
          type: string
          pattern: '^[a-z0-9]+(-[a-z0-9]+)*$'
        title:
          title: metadata.title
          type: string
        description:
          title: metadata.description
          type: string
        owner:
          title: spec.owner
          type: string
          description: group:team-name formatında
          ui:field: OwnerPicker

    - title: Standart metadata (opsiyonel)
      properties:
        tags:
          title: metadata.tags
          type: array
          items: { type: string }
        labels:
          title: metadata.labels (key/value)
          type: object
          additionalProperties: { type: string }
        annotations:
          title: metadata.annotations (key/value)
          type: object
          additionalProperties: { type: string }
        links:
          title: metadata.links
          type: array
          items:
            type: object
            required: [url, title]
            properties:
              url: { type: string }
              title: { type: string }
              icon: { type: string, description: 'optional (e.g. dashboard, docs, github)' }

    - title: Banka-özel (önerilen) metadata (opsiyonel ama çok değerli)
      properties:
        criticality:
          title: Criticality
          type: string
          enum: [tier-0, tier-1, tier-2, tier-3]
        dataClassification:
          title: Data Classification
          type: string
          enum: [restricted, confidential, internal, public]
        compliance:
          title: Compliance Tags
          type: array
          items:
            type: string
            enum: [pci, kvkk, psd2, sox, aml]
        oncall:
          title: Oncall (PagerDuty/Opsgenie/Slack)
          type: string
        runbookUrl:
          title: Runbook URL
          type: string
        dashboardUrl:
          title: Dashboard URL
          type: string
        logsUrl:
          title: Logs URL
          type: string
        tracesUrl:
          title: Traces URL
          type: string

    - title: Kind’e göre spec alanları (opsiyonel; ilgili kind için doldur)
      properties:
        # System/Component/API/Resource için
        domain:
          title: spec.domain (System için önerilir)
          type: string
        system:
          title: spec.system (Component/API/Resource için)
          type: string

        # Component için
        componentType:
          title: spec.type (Component)
          type: string
          enum: [service, website, mobile-app, worker, job, library, adapter, gateway]
        lifecycle:
          title: spec.lifecycle
          type: string
          enum: [experimental, production, deprecated]
        providesApis:
          title: spec.providesApis
          type: array
          items: { type: string }
        consumesApis:
          title: spec.consumesApis
          type: array
          items: { type: string }
        dependsOn:
          title: spec.dependsOn (component:xxx veya resource:yyy)
          type: array
          items: { type: string }

        # API için
        apiType:
          title: spec.type (API)
          type: string
          enum: [openapi, asyncapi, graphql, grpc]
        apiDefinitionInline:
          title: spec.definition (inline)
          type: string
          description: OpenAPI/AsyncAPI içeriğini buraya yapıştırabilirsin (opsiyonel).
          ui:widget: textarea
        apiDefinitionUrl:
          title: spec.definition ($text URL)
          type: string
          description: Spec bir URL’deyse buraya koy (opsiyonel).

        # Resource için
        resourceType:
          title: spec.type (Resource)
          type: string
          enum: [database, kafka-topic, queue, bucket, cache, kms-key, namespace, service-account]

        # Group için
        groupType:
          title: spec.type (Group)
          type: string
          enum: [team, business-unit, product-area, platform]
        parent:
          title: spec.parent (Group)
          type: string
        children:
          title: spec.children (Group)
          type: array
          items: { type: string }
        members:
          title: spec.members (Group)
          type: array
          items: { type: string }

  steps:
    - id: fetchRepo
      name: Fetch bank-catalog repo
      action: fetch:plain
      input:
        url: ${{ parameters.catalogRepoUrl }}
        targetPath: .

    - id: renderEntity
      name: Render entity yaml into data/
      action: fetch:template
      input:
        templateUrl: ./templates/entity-upsert/skeleton
        targetPath: .
        values:
          kind: ${{ parameters.kind }}
          kindDir: ${{ parameters.kind | lower }}s
          entityName: ${{ parameters.entityName }}
          title: ${{ parameters.title }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}

          tags: ${{ parameters.tags }}
          labels: ${{ parameters.labels }}
          annotations: ${{ parameters.annotations }}
          links: ${{ parameters.links }}

          criticality: ${{ parameters.criticality }}
          dataClassification: ${{ parameters.dataClassification }}
          compliance: ${{ parameters.compliance }}
          oncall: ${{ parameters.oncall }}
          runbookUrl: ${{ parameters.runbookUrl }}
          dashboardUrl: ${{ parameters.dashboardUrl }}
          logsUrl: ${{ parameters.logsUrl }}
          tracesUrl: ${{ parameters.tracesUrl }}

          domain: ${{ parameters.domain }}
          system: ${{ parameters.system }}
          componentType: ${{ parameters.componentType }}
          lifecycle: ${{ parameters.lifecycle }}
          providesApis: ${{ parameters.providesApis }}
          consumesApis: ${{ parameters.consumesApis }}
          dependsOn: ${{ parameters.dependsOn }}

          apiType: ${{ parameters.apiType }}
          apiDefinitionInline: ${{ parameters.apiDefinitionInline }}
          apiDefinitionUrl: ${{ parameters.apiDefinitionUrl }}

          resourceType: ${{ parameters.resourceType }}

          groupType: ${{ parameters.groupType }}
          parent: ${{ parameters.parent }}
          children: ${{ parameters.children }}
          members: ${{ parameters.members }}

    - id: pr
      name: Open Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.catalogRepoUrl }}
        branchName: catalog/${{ parameters.kind | lower }}-${{ parameters.entityName }}
        title: "catalog: upsert ${{ parameters.kind }} ${{ parameters.entityName }}"
        description: "Upsert entity in bank-catalog data/ via Backstage template."
        targetBranchName: main
        update: true
        sourcePath: .
        targetPath: .

  output:
    links:
      - title: Pull Request
        url: ${{ steps.pr.output.remoteUrl }}
